// memex setup --install-cli / --uninstall-cli contract:
//   - explicit flag required; never global installs; only ~/.local/bin touched
//   - refuses to overwrite or delete files it did not create (ownership marker)
//   - --dry-run writes nothing
//   - PATH absence produces a warning, not a failure
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const REPO = path.resolve(
  path.dirname(new URL(import.meta.url).pathname.replace(/^\/(?!\/)/, "/")),
  "..",
);
const SETUP = path.join(REPO, "scripts", "setup-memex.js");
const MARKER = "generated by memex setup --install-cli";

function fixture(t) {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "memex-setup-cli-"));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  return {
    binPath: path.join(home, ".local", "bin", "memex"),
    env: { ...process.env, HOME: home },
  };
}

test("--install-cli creates an executable owned shim and is idempotent", (t) => {
  const f = fixture(t);
  const out1 = execFileSync(process.execPath, [SETUP, "--install-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.match(out1, /Created .*\.local\/bin\/memex/);
  assert.match(out1, /You can now run: memex --help/);
  const st = fs.statSync(f.binPath);
  assert.equal(st.mode & 0o111, 0o111);
  const content1 = fs.readFileSync(f.binPath, "utf8");
  assert.ok(content1.includes(MARKER));
  assert.match(
    content1,
    /^exec npx --yes --package=github:BongSuCHOI\/memex#main memex "\$@"/m,
  );

  // Re-run refreshes the same owned file without error.
  execFileSync(process.execPath, [SETUP, "--install-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.equal(fs.readFileSync(f.binPath, "utf8"), content1);
});

test("--install-cli warns when ~/.local/bin is not on PATH but still succeeds", (t) => {
  const f = fixture(t);
  const env = { ...f.env, PATH: "/usr/bin:/bin" };
  const out = execFileSync(process.execPath, [SETUP, "--install-cli"], {
    env,
    encoding: "utf8",
  });
  assert.match(out, /not on your PATH/);
  assert.ok(fs.existsSync(f.binPath));
});

test("setup --install-cli refuses to overwrite a foreign file", (t) => {
  const f = fixture(t);
  fs.mkdirSync(path.dirname(f.binPath), { recursive: true });
  fs.writeFileSync(f.binPath, "#!/bin/sh\necho something-else\n", {
    mode: 0o755,
  });
  const bad = spawnSync(process.execPath, [SETUP, "--install-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /Refusing to overwrite existing unmanaged file/);
  assert.equal(
    fs.readFileSync(f.binPath, "utf8"),
    "#!/bin/sh\necho something-else\n",
  );
});

test("--uninstall-cli removes only owned shims and no-ops when absent", (t) => {
  const f = fixture(t);
  // absent -> friendly no-op
  const out = execFileSync(process.execPath, [SETUP, "--uninstall-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.match(out, /No CLI shim present/);

  fs.mkdirSync(path.dirname(f.binPath), { recursive: true });
  fs.writeFileSync(
    f.binPath,
    `#!/bin/sh\n# Memex CLI shim — ${MARKER}. Re-run memex setup to regenerate.\nexec true\n`,
    { mode: 0o755 },
  );
  const out2 = execFileSync(process.execPath, [SETUP, "--uninstall-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.match(out2, /Removed/);
  assert.equal(fs.existsSync(f.binPath), false);
});

test("setup --uninstall-cli refuses to delete foreign files", (t) => {
  const f = fixture(t);
  fs.mkdirSync(path.dirname(f.binPath), { recursive: true });
  fs.writeFileSync(f.binPath, "#!/bin/sh\necho mine\n", { mode: 0o755 });
  const bad = spawnSync(process.execPath, [SETUP, "--uninstall-cli"], {
    env: f.env,
    encoding: "utf8",
  });
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /Refusing to delete unmanaged file/);
  assert.ok(fs.existsSync(f.binPath));
});

test("--dry-run reports intent without writing anything", (t) => {
  const f = fixture(t);
  const out = execFileSync(
    process.execPath,
    [SETUP, "--install-cli", "--dry-run"],
    { env: f.env, encoding: "utf8" },
  );
  assert.match(out, /\[dry-run\] Would create\/refresh executable:/);
  assert.match(
    out,
    /exec npx --yes --package=github:BongSuCHOI\/memex#main memex "\$@"/,
  );
  assert.equal(fs.existsSync(f.binPath), false);
});

test("installing both directions together is rejected", (t) => {
  const f = fixture(t);
  const bad = spawnSync(
    process.execPath,
    [SETUP, "--install-cli", "--uninstall-cli"],
    { env: f.env, encoding: "utf8" },
  );
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /Choose either --install-cli or --uninstall-cli/);
});
