'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {Core}=require('../lib/core.cjs');const {fixture,uid,PROJECT}=require('./fixture.cjs');const fs=require('node:fs');const path=require('node:path');
function setup(){const f=fixture();const c=new Core({root:'/fixture/core',home:f.home,dbPath:'/fixture/db.sqlite'});c.db=f.db;c.store=f.store;let calls=[],closed=0;const writer={close(){closed++;}};c.modules.set('db',{openWriteDb(p){calls.push(['writer',p]);return writer;}});c.modules.set('fact-management',{async mutateFactMeaning(db,opts){calls.push(['edit',db,opts]);return {id:opts.factId,revisionId:'mock-revision',embeddingRefreshed:true};},deactivateFactTransactional(db,id){calls.push(['deactivate',db,id]);return {deactivated:true};},async restoreFact(db,id){calls.push(['restore',db,id]);return {restored:true};},async hardDeleteFact(db,id,opts){calls.push(['delete',db,id,opts]);return {deleted:true};},hardDeleteImpact(db,id){return {exists:true,revisions:2};}});return {f,c,calls,closed:()=>closed,scope:f.store.scope(new URLSearchParams({scope:'project',project:PROJECT})),clean(){c.close();fs.rmSync(f.home,{recursive:true,force:true});}};}
test('root resolution points at the repository containing ui, not its parent',()=>{const c=new Core({home:'/tmp/unused'});if(!process.env.MEMEX_PLUGIN_ROOT&&!process.env.PLUGIN_ROOT)assert.equal(c.root,path.resolve(__dirname,'../..'));});
test('explicit user edit uses shared service, both CAS generations and human rationale',async()=>{const x=setup();try{const old=x.f.store.visibleFact(uid(1),x.scope);await x.c.mutate({id:uid(1),action:'edit',text:'Updated factual content',reason:'A user correction',expectedText:old.fact,expectedUpdatedAt:old.updated_at},x.scope);const [,writer,o]=x.calls.find(c=>c[0]==='edit');assert.equal(o.expectedPreviousFact,old.fact);assert.equal(o.expectedSemanticGeneration,old.semantic_generation);assert.equal(o.expectedLifecycleGeneration,old.lifecycle_generation);assert.equal(o.chronicle.actor,'user');assert.equal(o.chronicle.evidenceAuthority,'human');assert.equal(o.chronicle.userStatedRationale,'A user correction');assert.equal(x.closed(),1);assert.equal(x.c.busy.size,0);}finally{x.clean();}});
test('stale edits and cross-scope changes never open a writer',async()=>{const x=setup();try{await assert.rejects(x.c.mutate({id:uid(1),action:'edit',text:'Updated text',expectedText:'stale'},x.scope),{status:409});await assert.rejects(x.c.mutate({id:uid(73),action:'deactivate'},x.scope),{status:404});assert.equal(x.calls.length,0);}finally{x.clean();}});
test('deactivate and restore use core lifecycle services',async()=>{const x=setup();try{await x.c.mutate({id:uid(1),action:'deactivate'},x.scope);await x.c.mutate({id:uid(1),action:'restore'},x.scope);assert(x.calls.some(c=>c[0]==='deactivate'));assert(x.calls.some(c=>c[0]==='restore'));assert.equal(x.closed(),2);}finally{x.clean();}});
test('hard delete requires full exact ID and explicit confirmation',async()=>{const x=setup();try{await assert.rejects(x.c.mutate({id:uid(1),action:'delete',confirm:true,confirmId:'wrong'},x.scope),{status:400});assert.equal(x.calls.length,0);await x.c.mutate({id:uid(1),action:'delete',confirm:true,confirmId:uid(1)},x.scope);assert.deepEqual(x.calls.find(c=>c[0]==='delete')[3],{confirm:true});}finally{x.clean();}});
test('core failure closes writer and clears busy state',async()=>{const x=setup();try{x.c.modules.get('fact-management').mutateFactMeaning=async()=>{throw new Error('Embedding not available (mock)');};await assert.rejects(x.c.mutate({id:uid(1),action:'edit',text:'Updated content'},x.scope),/Embedding not available/);assert.equal(x.closed(),1);assert.equal(x.c.busy.size,0);}finally{x.clean();}});
test('no DB file is created when the initial read fails',async()=>{const f=fixture(),filename=path.join(f.home,'missing','never.sqlite');const c=new Core({root:f.home,dbPath:filename,home:f.home});try{await assert.rejects(c.connect(),{status:503});assert.equal(fs.existsSync(filename),false);}finally{f.close();fs.rmSync(f.home,{recursive:true,force:true});}});
test('API helper sends POST plus token when a body exists',async()=>{const mod=await import('../public/api.mjs');const saved={fetch:global.fetch,location:global.location};try{global.location={origin:'http://127.0.0.1:3847'};let captured;global.fetch=async(url,opts)=>{captured={url:String(url),opts};return new Response('{"ok":true}',{status:200,headers:{'content-type':'application/json'}});};mod.setToken('test-token');assert.deepEqual(await mod.request('facts/mutate',{scope:'global'},{body:{action:'edit'}}),{ok:true});assert.equal(captured.opts.method,'POST');assert.equal(captured.opts.headers['X-Memex-CSRF'],'test-token');await mod.request('facts');assert.equal(captured.opts.method,'GET');assert.equal(captured.opts.body,undefined);}finally{global.fetch=saved.fetch;global.location=saved.location;}});
test('safe Markdown escapes scripts, event attributes and remote image syntax',async()=>{const {markdown,esc}=await import('../public/ui.mjs');const html=markdown('<img src=x onerror=alert(1)>\n\n<script>alert(2)</script>\n\n![remote](https://invalid/x)');assert(!html.includes('<img'));assert(!html.includes('<script'));assert(html.includes('&lt;script&gt;'));assert.equal(esc('"\'<>&'),'&quot;&#39;&lt;&gt;&amp;');});

test('initial missing DB can be retried after sync creates it',async()=>{const f=fixture(),filename=path.join(f.home,'created-later.sqlite');const c=new Core({root:f.home,dbPath:filename,home:f.home});try{await assert.rejects(c.connect(),{status:503});assert.equal(c.connecting,null);fs.writeFileSync(filename,'fixture marker');c.modules.set('db',{openReadDb(){return f.db;}});const store=await c.connect(true);assert.equal(store.db,f.db);assert.equal(c.connecting,null);}finally{c.close();fs.rmSync(f.home,{recursive:true,force:true});}});
test('an explicitly pointed database owns the UI home, so a temp DB never writes into the real one',()=>{
 const saved={};for(const k of ['MEMEX_HOME','MEMEX_DB_PATH','TEST_DB_PATH','XDG_CONFIG_HOME'])saved[k]=process.env[k];
 try{
  delete process.env.MEMEX_HOME;delete process.env.TEST_DB_PATH;process.env.XDG_CONFIG_HOME=path.join('/fixture','xdg');
  process.env.MEMEX_DB_PATH=path.join('/fixture','scratch','db.sqlite');
  assert.equal(new Core().home,path.join('/fixture','scratch'));
  process.env.MEMEX_DB_PATH=path.join('/fixture','scratch','conversation-index','db.sqlite');
  assert.equal(new Core().home,path.join('/fixture','scratch'));
  process.env.MEMEX_HOME=path.join('/fixture','explicit');
  assert.equal(new Core().home,path.join('/fixture','explicit'));
  delete process.env.MEMEX_HOME;delete process.env.MEMEX_DB_PATH;
  assert.equal(new Core().home,path.join('/fixture','xdg','memex'));
 }finally{for(const [k,v] of Object.entries(saved)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}
});
