'use strict';
/** TEST DATA ONLY. Production never imports this module. No real prompts or records. */
const {DatabaseSync}=require('node:sqlite');const {Store}=require('../lib/store.cjs');const {HttpError}=require('../lib/util.cjs');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const PROJECT='/workspace/memex',OTHER='/workspace/design-system';const uid=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const schemas={
 projects:'project_id!,portable_project_key,display_name,memory_revision#,created_at,updated_at',
 workspaces:'workspace_id!,project_id,canonical_path,branch,last_seen_at',
 minimal_workstreams:'workstream_id!,project_id,workspace_id,project,session_id,branch_hint,binding_reason,created_at,updated_at',
 work_capsules:'workstream_id!,generation#,objective,current_state,next_actions,authority,updated_at',
 exchanges:'id!,project,project_id,workspace_id,workstream_id,session_id,timestamp,user_message,assistant_message,cwd,git_branch,archive_path,line_start#,line_end#,exchange_seq#,content_generation#,content_hash,closure_state,provenance',
 tool_calls:'id!,exchange_id,tool_name,tool_input,tool_result,is_error#,timestamp,source_type,learnable#',
 facts:'id!,fact,fact_kr,category,scope_type,scope_project,project_id,workspace_id,workstream_id,promotion_state,tier_reason,subject_key,is_active#,ontology_category_id,source_exchange_ids,consolidated_count#,created_at,updated_at,semantic_generation#,lifecycle_generation#,embedding_version,needs_consolidation#',
 ontology_domains:'id!,name,description',ontology_categories:'id!,domain_id,name,description',ontology_relations:'id!,source_fact_id,relation_type,target_fact_id,reasoning,created_at',
 fact_revisions:'id!,fact_id,previous_fact,new_fact,reason,source_exchange_id,created_at,project_id,subject_key,event_kind,from_semantic_generation#,to_semantic_generation#,lifecycle_generation#,problem,grounded_cause,rationale,classifier_note,outcome_json,source_exchange_ids,source_evidence_ids,reverts_event_id,related_event_ids,actor,policy_version,evidence_authority,effective_at,effective_at_source,recorded_at,projection_applied#,chronicle_seq#',
 fact_context_dependencies:'fact_id,exchange_id,dependency_kind,created_at',fact_evidence_receipts:'fact_id!,semantic_generation#,fact_hash,source_snapshot_json,method,verified_at',
 extraction_log:'session_id!,processed_at,extracted#,saved#,dropped_batches#,claim_owner,last_exchange_rowid#',
 recall_events:'id!,session_id,project,prompt_hash,fact_ids,source_type,learnable#,status,created_at,emitted_at',
 checkpoints:'checkpoint_id!,session_id,workspace_id,workstream_id,kind,state,closure_state,created_at',
 memory_jobs:'job_id!,kind,partition_key,checkpoint_id,target_id,from_cursor,through_cursor,policy_version,priority#,state,available_at,lease_owner,lease_until,lease_generation#,attempts#,max_attempts#,last_error,idempotency_key,created_at,updated_at,budget_id,maintenance_wave_id',
 extraction_targets:'target_id!,session_id,project,from_rowid#,through_rowid#,cursor_ordinal#,item_count#,policy_version,state,lease_owner,lease_until,lease_generation#,attempts#,last_error,idempotency_key,created_at,updated_at',
 extraction_target_items:'target_id,ordinal#,exchange_id,exchange_rowid#,content_generation#,content_hash,state',
 exchange_extraction_state:'exchange_id,content_generation#,policy_version,state,target_id,processed_at',
 extraction_failed_ranges:'failure_id!,target_id,from_ordinal#,through_ordinal#,from_rowid#,through_rowid#,payload_fingerprint,error_kind,error_message,state,attempts#,created_at,updated_at',
 model_work_budgets:'budget_id!,parent_wave_id,state,max_attempts#,reserved_attempts#,max_input_chars#,max_output_chars#,deadline_at,created_at,updated_at',
 model_work_attempts:'attempt_id!,budget_id,attempt_no#,stage,job_id,target_id,state,started_at,finished_at,duration_ms#,input_chars#,output_chars#,token_usage_json,token_usage_status,error_class,error_message',
};
function fixture(options={}){
 const home=options.home||fs.mkdtempSync(path.join(os.tmpdir(),'memex-ui-test-')),filename=options.filename||':memory:';const db=new DatabaseSync(filename);
 for(const[t,definition]of Object.entries(schemas))db.exec(`CREATE TABLE ${t} (${definition.split(',').map(c=>`"${c.replace(/[#!]/g,'')}" ${c.includes('#')?'INTEGER':'TEXT'}${c.includes('!')?' PRIMARY KEY':''}`).join(',')})`);
 const insert=(t,o)=>{const keys=Object.keys(o);db.prepare(`INSERT INTO ${t} (${keys.map(x=>'"'+x+'"').join(',')}) VALUES (${keys.map(()=>'?').join(',')})`).run(...Object.values(o));};
 const now=Date.now(),ts=(minutes=0)=>new Date(now-minutes*60000).toISOString();
 const themes=[['기억의 근거와 추출 경로 연결하기','팩트에서 원문 대화로 이동하고, 원문에서 실제 추출 작업으로 연결하는 방식으로 구현하자.'],['SQLite 읽기와 쓰기 경계 정리','조회 화면에서는 openReadDb만 사용하고, 기억 변경은 공통 서비스를 통과하도록 해줘.'],['프로젝트 범위와 공통 기억 구분','현재 프로젝트에 공통 기억을 포함할 수 있게 하되, 다른 프로젝트의 대화는 섞이면 안 돼.'],['온톨로지 관계 탐색 개선','지도는 2D 탐색을 기본으로 두고 필요할 때 3D로 전환하자. 관계 유형과 방향을 읽을 수 있어야 해.'],['추출 실패와 모델 예산 점검','실패를 숨기지 말고 재시도 상태와 입력 버전을 같이 보여줘. 수집되지 않은 토큰 수는 0으로 표시하지 말자.'],['대화 원장 탐색 흐름 설계','세션별로 대화를 읽고 직접 근거, 해석 맥락, 제공된 기억을 구분해서 볼 수 있게 하자.'],['로컬 관리 작업 안전장치','동기화와 백필은 자동 실행하지 말고 전체 범위와 영향을 확인한 뒤 시작해야 해.'],['지식 변경의 시간 기준 정리','사건이 발생한 시각과 Memex가 기록한 시각을 분리해 보여주자.'],['한국어 우선 표시와 검색','저장된 한국어 번역이 있으면 먼저 보여주고 원문도 펼쳐서 볼 수 있도록 해줘.'],['UI 진단 내보내기','진단 파일에는 버전과 기능 상태만 넣고 대화 본문과 로컬 경로는 제외하자.'],['접근성과 키보드 탐색 점검','검색은 단축키로 열고 상세 패널은 Esc로 닫을 수 있어야 해.'],['로그 관측 범위 설정','프로젝트 ID가 없는 일반 로그는 전체 범위를 명시적으로 선택했을 때만 보여주자.']];
 for(let k=0;k<2;k++){insert('projects',{project_id:'project-'+k,portable_project_key:'fixture-'+k,display_name:k?'Design system':'Memex',memory_revision:20,created_at:ts(30000),updated_at:ts()});insert('workspaces',{workspace_id:'workspace-'+k,project_id:'project-'+k,canonical_path:k?OTHER:PROJECT,branch:k?'develop':'main',last_seen_at:ts()});}
 for(let s=0;s<16;s++){const k=s>=12?1:0,session='session-'+s;insert('minimal_workstreams',{workstream_id:'stream-'+s,project_id:'project-'+k,workspace_id:'workspace-'+k,project:k?OTHER:PROJECT,session_id:session,branch_hint:k?'tokens':'ui/redesign',binding_reason:'fixture',created_at:ts(s*1400+35),updated_at:ts(s*1400)});const theme=themes[s%12];
 for(let t=0;t<(s===0?26:5);t++){const n=s*100+t,id='exchange-'+n,age=s*1400+(s===0?25-t:4-t)*8+2;insert('exchanges',{id,project:k?OTHER:PROJECT,project_id:'project-'+k,workspace_id:'workspace-'+k,workstream_id:'stream-'+s,session_id:session,timestamp:ts(age),user_message:t===0?`## ${theme[0]}\n\n${theme[1]}`:t%3===0?`근거를 확인할 수 있도록 원문 버전과 작업 ID도 함께 남겨줘. 이것은 검증용 예제 대화 ${s+1}의 ${t+1}번째 턴이야.`:theme[1],assistant_message:`**${theme[0]}** 방향으로 연결하겠습니다.\n\n기억의 현재 내용과 직접 근거를 분리하고, 실제 기록에 연결된 정보만 보여주겠습니다.\n\n\`\`\`ts\nconst scope = { project: 'memex', includeGlobal: true };\n\`\`\``,cwd:k?OTHER:PROJECT,git_branch:k?'develop':'ui/redesign',archive_path:'/fixture/archive/'+session+'.jsonl',line_start:t*2+1,line_end:t*2+2,exchange_seq:t,content_generation:1,content_hash:'sha256:fixture-'+n,closure_state:'closed',provenance:'fixture'});if(t<5)insert('exchange_extraction_state',{exchange_id:id,content_generation:1,policy_version:'facts-v4',state:s===4?'retry':'processed',target_id:'target-'+s,processed_at:s===4?null:ts(age-1)});}
 insert('extraction_log',{session_id:session,processed_at:ts(s*1400),extracted:5,saved:3,dropped_batches:0,last_exchange_rowid:s*100+4});insert('checkpoints',{checkpoint_id:'checkpoint-'+s,session_id:session,workspace_id:'workspace-'+k,workstream_id:'stream-'+s,kind:'stop',state:'completed',closure_state:'closed',created_at:ts(s*1400+1)});
 const state=s===0?'running':s===4?'retry':s===7?'dead':'completed',error=state==='retry'?'MODEL_BUDGET_EXHAUSTED: deadline reached':state==='dead'?'Invalid evidence references after retries':null;
 insert('extraction_targets',{target_id:'target-'+s,session_id:session,project:k?OTHER:PROJECT,from_rowid:s*100+1,through_rowid:s*100+5,cursor_ordinal:0,item_count:5,policy_version:'facts-v4',state,lease_owner:state==='running'?'worker-fixture':null,lease_until:state==='running'?ts(-3):null,lease_generation:1,attempts:state==='retry'?2:1,last_error:error,idempotency_key:'fixture-target-'+s,created_at:ts(s*1400+2),updated_at:ts(s*1400)});
 insert('model_work_budgets',{budget_id:'budget-'+s,state:state==='retry'?'exhausted':state==='running'?'active':'completed',max_attempts:12,reserved_attempts:state==='retry'?12:1,max_input_chars:60000,max_output_chars:16000,deadline_at:ts(s*1400-10),created_at:ts(s*1400+2),updated_at:ts(s*1400)});
 insert('memory_jobs',{job_id:'job-'+s,kind:'fact_extract',partition_key:'session:'+session,checkpoint_id:'checkpoint-'+s,target_id:'target-'+s,from_cursor:'0',through_cursor:'5',policy_version:'facts-v4',priority:100,state,available_at:ts(s*1400-5),lease_owner:state==='running'?'worker-fixture':null,lease_until:state==='running'?ts(-3):null,lease_generation:1,attempts:state==='retry'?2:1,max_attempts:5,last_error:error,idempotency_key:'fixture-job-'+s,created_at:ts(s*1400+2),updated_at:ts(s*1400),budget_id:'budget-'+s});
 for(let t=0;t<5;t++)insert('extraction_target_items',{target_id:'target-'+s,ordinal:t,exchange_id:'exchange-'+(s*100+t),exchange_rowid:s*100+t+1,content_generation:1,content_hash:'sha256:fixture-'+(s*100+t),state:s===4?'retry':s===0?'processing':'processed'});
 insert('model_work_attempts',{attempt_id:'attempt-'+s,budget_id:'budget-'+s,attempt_no:1,stage:'fact-extraction',job_id:'job-'+s,target_id:s===2?null:'target-'+s,state:state==='running'?'reserved':state==='retry'||state==='dead'?'failed':'completed',started_at:ts(s*1400+1),finished_at:state==='running'?null:ts(s*1400),duration_ms:state==='running'?null:2840+s*133,input_chars:4200+s*250,output_chars:state==='running'?null:600+s*33,token_usage_json:s%3===0?null:JSON.stringify({input_tokens:1220+s*22,output_tokens:230+s*7}),token_usage_status:s%3===0?'NOT_PROVEN':'observed',error_class:state==='retry'?'deadline_exceeded':null,error_message:state==='retry'?'Model work deadline exceeded':null});
 if(s===4)insert('extraction_failed_ranges',{failure_id:'failure-4',target_id:'target-4',from_ordinal:0,through_ordinal:4,from_rowid:401,through_rowid:405,payload_fingerprint:'fixture-payload',error_kind:'model_budget',error_message:'작업 기한을 초과해 현재 범위를 재시도 대상으로 남겼습니다.',state:'retry',attempts:2,created_at:ts(5610),updated_at:ts(5600)});
 }
 insert('work_capsules',{workstream_id:'stream-0',generation:2,objective:'기억의 출처와 처리 경로를 한 작업 화면에서 따라갈 수 있는 로컬 UI 구성',current_state:'근거와 작업 추적을 연결하고 읽기 범위 경계를 점검하는 중',next_actions:'["근거 연결 검증","관리 실행 확인"]',authority:'context-only',updated_at:ts(3)});
 insert('tool_calls',{id:'tool-0',exchange_id:'exchange-0',tool_name:'read_file',tool_input:'{"path":"src/db.ts"}',tool_result:'// 검증용 예제 도구 출력',is_error:0,timestamp:ts(200),source_type:'tool',learnable:0});
 const domains=[['engineering','엔지니어링','코어, 저장소, 런타임과 데이터 처리'],['product','제품 · 경험','탐색 구조와 사용자 경험'],['operations','운영 · 신뢰','관측, 안전장치와 진단'],['workflow','작업 방식','프로젝트 운영과 개인 선호']];domains.forEach(([id,name,description])=>insert('ontology_domains',{id,name,description}));
 const categories=[['storage','engineering','데이터 저장소','SQLite 접근과 데이터 일관성'],['scope','engineering','기억 범위','프로젝트·공통·워크스페이스 경계'],['extraction','engineering','추출 파이프라인','입력 버전, 근거 검증과 저장'],['navigation','product','정보 구조','대화에서 기억으로 이어지는 탐색'],['graph','product','지식 시각화','관계 유형과 온톨로지 지도'],['reading','product','읽기 경험','한국어·밀도·접근성'],['observability','operations','관측 · 추적','작업 실행과 지식 변경 이력'],['security','operations','로컬 안전','동일 출처와 변경 작업 안전장치'],['diagnostics','operations','진단 · 로그','실제 상태와 미수집 정보의 구분'],['preferences','workflow','작업 선호','개인 선호와 반복 작업 패턴']];categories.forEach(([id,domain_id,name,description])=>insert('ontology_categories',{id,domain_id,name,description}));
 const content=['대화에서 추출한 기억은 직접 근거와 해석에 참고한 맥락을 분리해서 표시한다.','조회 경로는 openReadDb를 사용하고 기억 변경은 공통 코어 서비스를 통과한다.','프로젝트별 기억과 공통 기억을 구분하고 다른 프로젝트의 대화 원문을 섞지 않는다.','지식 지도는 2D 관계 탐색을 기본으로 제공하고 3D 보기를 선택할 수 있다.','모델 시도의 입력 버전, 실제 소요 시간, 오류 원인을 기록한다.','대화 원장은 메시지보다 세션을 기본 탐색 단위로 사용한다.','대화 동기화와 백필은 사용자가 실행 범위와 영향을 확인한 후 시작한다.','지식 변화의 발생 시각과 데이터베이스에 기록된 시각을 별도로 보여준다.','한국어 번역이 저장된 기억은 한국어로 먼저 표시하고 원문도 확인할 수 있다.','진단 내보내기에 대화 원문, 팩트 문장, 환경 비밀정보를 포함하지 않는다.','기억 상세는 키보드와 스크린 리더로 탐색할 수 있어야 한다.','프로젝트에 연결되지 않은 로그는 전체 프로젝트 범위에서만 조회한다.'];
 for(let i=0;i<84;i++){const k=i>=72?1:0,global=i>=66&&i<72,si=i%12+(k?4:0),source='exchange-'+(si*100+i%5),cat=categories[(i+2)%categories.length][0];let text=content[i%12];if(i>=12)text+=` ${['운영 정책','화면 규칙','추출 규칙','설계 결정','적용 원칙','검증 기준'][Math.floor(i/12)-1]||'공통 원칙'} ${i+1}.`;
 insert('facts',{id:uid(i+1),fact:i%5===0?'Memex separates authoritative evidence from interpretive context. '+text:text,fact_kr:i%5===0?text:null,category:['decision','knowledge','constraint','pattern','preference'][i%5],scope_type:global?'global':'project',scope_project:global?null:k?OTHER:PROJECT,project_id:global?null:'project-'+k,workspace_id:global?null:'workspace-'+k,workstream_id:global?null:'stream-'+si,promotion_state:i===64?'workspace':i===65?'workstream':i===63?'project-current':'legacy-project',tier_reason:i===65?'branch:feature/tier-ladder':i===64?'no-branch-signal':i===63?'default-branch':null,subject_key:'memex.'+cat+'.'+i,is_active:i%19===18?0:1,ontology_category_id:i%13===12?null:cat,source_exchange_ids:JSON.stringify([source]),consolidated_count:i%5+1,created_at:ts(9000+i*13),updated_at:ts(i*34+4),semantic_generation:i%3+1,lifecycle_generation:1,embedding_version:'fixture-vector-v1',needs_consolidation:i%13===12?1:0});
 insert('fact_revisions',{id:'event-'+i,fact_id:uid(i+1),previous_fact:i%3===0?'대화와 기억을 별도 화면에서 조회한다.':null,new_fact:text,reason:null,source_exchange_id:source,created_at:ts(i*34+4),project_id:global?null:'project-'+k,subject_key:'memex.'+cat+'.'+i,event_kind:i%3===0?'CHANGED':'ASSERTED',from_semantic_generation:i%3===0?1:null,to_semantic_generation:i%3+1,lifecycle_generation:1,rationale:i%3===0?'사용자가 근거를 따라가며 기억을 확인할 수 있도록 한다.':null,source_exchange_ids:JSON.stringify([source]),source_evidence_ids:'[]',related_event_ids:'[]',actor:i%3===0?'user':'extractor',policy_version:'facts-v4',evidence_authority:'human',effective_at:ts(i*34+120),effective_at_source:'source',recorded_at:ts(i*34+4),projection_applied:1,chronicle_seq:i+1});
 insert('fact_evidence_receipts',{fact_id:uid(i+1),semantic_generation:i%3+1,fact_hash:'sha256:fixture-fact-'+i,source_snapshot_json:JSON.stringify([{id:source,text:'fixture source snapshot'}]),method:'extractor',verified_at:ts(i*34+4)});
 if(i<12)insert('fact_context_dependencies',{fact_id:uid(i+1),exchange_id:'exchange-'+(i*100+1),dependency_kind:'assistant_context',created_at:ts(i*34+4)});
 if(i>0&&i<65){insert('ontology_relations',{id:'relation-'+i,source_fact_id:uid(i+1),relation_type:['SUPPORTS','INFLUENCES','SUPERSEDES','CONTRADICTS'][i%4],target_fact_id:uid(Math.max(1,i-6)),reasoning:'검증용 예제: 같은 설계 원칙을 서로 다른 관점에서 설명하는 기억입니다.',created_at:ts(i*34+3)});if(i>8)insert('ontology_relations',{id:'relation-extra-'+i,source_fact_id:uid(i+1),relation_type:'SUPPORTS',target_fact_id:uid(i-8),reasoning:'검증용 관계',created_at:ts(i*34+3)});}
 }
 for(let i=0;i<12;i++)insert('recall_events',{id:'recall-'+i,session_id:'session-'+i,project:PROJECT,prompt_hash:'sha256:fixture-prompt-'+i,fact_ids:JSON.stringify([uid(i+1),uid(i+13)]),source_type:'memex_recall',learnable:0,status:i===0?'prepared':'emitted',created_at:ts(i*1400+4),emitted_at:i===0?null:ts(i*1400+3)});
 fs.mkdirSync(path.join(home,'logs'),{recursive:true});fs.writeFileSync(path.join(home,'logs','inject-context.jsonl'),Array.from({length:60},(_,i)=>JSON.stringify({ts:ts(i*13),status:i%11===0?'no-match':i%9===0?'deduped':i%7===0?'error':'injected',project:i%8===0?OTHER:PROJECT,prompt_len:184+i,candidates:i%11===0?0:6,injected:i%11===0||i%9===0||i%7===0?0:3,deduped:i%9===0?3:0,chars:840+i*9,duration_ms:24+i,error:i%7===0?'검증용 예제: embedding runtime unavailable':undefined,via:'fixture-hook',gate:'eligible'})).join('\n')+'\n');fs.writeFileSync(path.join(home,'logs','runtime.log'),'2026-09-09 example unscoped diagnostic line\n');
 const store=new Store(db);return {db,store,home,filename,insert,ts,uid,PROJECT,OTHER,close(){try{db.close();}catch{}}};
}
class FixtureCore{
 constructor(f){Object.assign(this,{fixture:f,root:path.resolve(__dirname,'../../..'),home:f.home,dbPath:f.filename===':memory:'?path.join(f.home,'db.sqlite'):f.filename,db:f.db,store:f.store,version:'0.4.2 · fixture',busy:new Set()});}
 async connect(){return this.store;}environment(){return {root:this.root,home:this.home,dbPath:this.dbPath,version:this.version,node:process.version,platform:process.platform,pid:process.pid,values:{MEMEX_AUTO_ONTOLOGY:null,MEMEX_MODEL_BUDGET_MAX_ATTEMPTS:null},autoOntology:false,mutable:false,commands:false,sync:true,demo:true,note:'검증용 환경입니다. 실제 플러그인을 실행하지 않습니다.'};}
 async pipeline(){const a=this.store.overview(this.store.scope(new URLSearchParams({scope:'all'})));return {dataRootEmpty:false,conversations:{sessionsIndexed:a.sessions,exchanges:a.exchanges,archiveFiles:16,ready:true},extraction:{total:16,done:13,pending:1,excluded:0,deferred:0,claimed:1,failedPermanent:1,retriable:1,lastSuccessAt:this.fixture.ts(34)},embeddings:{activeFacts:a.facts.active,factVectorsPending:6},ontology:{classifiedFacts:a.facts.active-a.facts.unclassified,pendingFacts:a.facts.unclassified},relations:{total:120},readiness:{conversationReady:true,factReady:true,graphReady:true},lifecycleLastEventAt:this.fixture.ts(4)};}
 async mutate(){throw new HttpError(403,'검증용 예제에서는 실제 코어 변경을 실행하지 않습니다.','FIXTURE_READ_ONLY');}
 async tier(){throw new HttpError(403,'검증용 예제에서는 실제 코어 변경을 실행하지 않습니다.','FIXTURE_READ_ONLY');}
 async sync(action){
  if(action!=='status')throw new HttpError(403,'검증용 예제에서는 실제 코어 변경을 실행하지 않습니다.','FIXTURE_READ_ONLY');
  return {status:{enabled:false,dir:path.join(this.home,'conversation-index','sync'),dirSource:'default',dirExists:false,dirWritable:false,configPath:path.join(this.home,'sync','config.json'),updatedAt:null,deviceId:null,lastExport:null,peers:[]}};
 }async impact(id,s){this.store.visibleFact(id,s);return {exists:true,revisions:1,relations:2,contextDependencies:1};}close(){this.fixture.close();}
}
module.exports={fixture,FixtureCore,uid,PROJECT,OTHER};
