#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import { join } from "node:path";
import readline from "node:readline/promises";
import { stdin, stdout } from "node:process";

const SHIM_MARKER = "generated by memex setup --install-cli";

function runCodex(args) {
  return spawnSync("codex", args, { encoding: "utf8" });
}

function memoryEnabled() {
  const result = runCodex(["features", "list"]);
  if (result.error)
    throw new Error(`Could not run Codex CLI: ${result.error.message}`);
  if (result.status !== 0)
    throw new Error(
      `Could not inspect Codex features: ${(result.stderr || result.stdout).trim()}`,
    );
  const line = result.stdout
    .split(/\r?\n/)
    .find((entry) => /^memories\s/.test(entry));
  if (!line)
    throw new Error(
      "This Codex version does not expose the memories feature; no setting was changed.",
    );
  return /\btrue\s*$/.test(line.trim());
}

async function approvedByUser() {
  if (!stdin.isTTY || !stdout.isTTY) return false;
  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    const answer = await rl.question(
      "Disable Codex built-in Memory now? [y/N] ",
    );
    return /^(y|yes)$/i.test(answer.trim());
  } finally {
    rl.close();
  }
}

// ── Optional CLI shim (~/.local/bin/memex) ────────────────────────────────
// Opt-in convenience so users do not need an npx shell function. Creating or
// removing it always requires an explicit flag; nothing is ever installed
// globally, and Memex data/hooks/Codex rollouts are untouched.

function userHome() {
  // Deterministic across shells (tests set HOME explicitly).
  return process.env.HOME || os.homedir();
}

export function cliBinDir(home = userHome()) {
  return join(home, ".local", "bin");
}

export function cliBinPath(home = userHome()) {
  return join(cliBinDir(home), "memex");
}

export function renderCliShim() {
  return [
    "#!/bin/sh",
    "# Memex CLI shim — " + SHIM_MARKER + ". Re-run memex setup to regenerate.",
    'exec npx --yes --package=github:BongSuCHOI/memex#main memex "$@"',
    "",
  ].join("\n");
}

function isOwnedShim(p) {
  let content = "";
  try {
    content = readFileSync(p, "utf8");
  } catch {
    return false;
  }
  return content.includes(SHIM_MARKER);
}

function warnIfNotOnPath(binDir) {
  const paths = (process.env.PATH || "").split(":").filter(Boolean);
  if (!paths.includes(binDir)) {
    console.log(`NOTE: ${binDir} is not on your PATH. Add it, e.g.:`);
    console.log(`  fish:      fish_add_path ${binDir}`);
    console.log(
      `  zsh/bash:  echo 'export PATH="${binDir}:$PATH"' >> ~/.zshrc`,
    );
  }
}

function installCli({ dryRun }) {
  const binPath = cliBinPath();
  const binDir = cliBinDir();
  if (existsSync(binPath) && !isOwnedShim(binPath)) {
    throw new Error(
      `Refusing to overwrite existing unmanaged file: ${binPath} (not generated by memex)`,
    );
  }
  if (dryRun) {
    console.log("[dry-run] Would create/refresh executable:", binPath);
    console.log(renderCliShim());
    return;
  }
  mkdirSync(binDir, { recursive: true });
  writeFileSync(binPath, renderCliShim(), { mode: 0o755 });
  console.log(`Created ${binPath}. You can now run: memex --help`);
  warnIfNotOnPath(binDir);
}

function uninstallCli({ dryRun }) {
  const binPath = cliBinPath();
  if (!existsSync(binPath)) {
    console.log(`No CLI shim present at ${binPath}. Nothing removed.`);
    return;
  }
  if (!isOwnedShim(binPath)) {
    throw new Error(
      `Refusing to delete unmanaged file: ${binPath} (not generated by memex)`,
    );
  }
  if (dryRun) {
    console.log("[dry-run] Would remove:", binPath);
    return;
  }
  rmSync(binPath);
  console.log(`Removed ${binPath}.`);
}

// ── Entry point ─────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  if (args.includes("--help") || args.includes("-h")) {
    console.log(`Usage: memex setup [--dry-run] [--disable-codex-memory]
                    [--install-cli | --uninstall-cli]

Detect the effective Codex built-in memories feature. No setting changes unless
you approve interactively or pass --disable-codex-memory explicitly.

--install-cli     Create ~/.local/bin/memex so you can run \`memex\` without an
                  npx shell function. Never installed globally; PATH is checked.
--uninstall-cli   Remove that shim (only files this command created).`);
    return;
  }
  const explicitApproval = args.includes("--disable-codex-memory");
  const dryRun = args.includes("--dry-run");
  const unknown = args.filter(
    (arg) =>
      ![
        "--disable-codex-memory",
        "--dry-run",
        "--install-cli",
        "--uninstall-cli",
      ].includes(arg),
  );
  if (unknown.length > 0)
    throw new Error(`Unknown setup option: ${unknown[0]}`);

  // CLI shim management is independent of Codex features; run it first and
  // short-circuit when nothing else was requested.
  const wantsInstall = args.includes("--install-cli");
  const wantsUninstall = args.includes("--uninstall-cli");
  if (wantsInstall && wantsUninstall) {
    throw new Error(
      "Choose either --install-cli or --uninstall-cli, not both.",
    );
  }
  if (wantsInstall || wantsUninstall) {
    (wantsInstall ? installCli : uninstallCli)({ dryRun });
    const remaining = args.filter(
      (a) => !["--install-cli", "--uninstall-cli", "--dry-run"].includes(a),
    );
    if (remaining.length === 0) return;
  }

  if (!memoryEnabled()) {
    console.log(
      "Codex built-in Memory is already disabled. No memory setting changed.",
    );
    return;
  }

  console.log(
    "Codex built-in Memory is enabled. Running it with Memex can create duplicate or conflicting recall.",
  );
  console.log(
    "Recommendation: disable Codex built-in Memory while Memex is active.",
  );
  if (dryRun) {
    console.log("[dry-run] Would run: codex features disable memories");
    console.log("No setting changed.");
    return;
  }

  const approved = explicitApproval || (await approvedByUser());
  if (!approved) {
    console.log(
      "Codex built-in Memory was left enabled. To approve the change explicitly, run:",
    );
    console.log("  memex setup --disable-codex-memory");
    return;
  }

  const result = runCodex(["features", "disable", "memories"]);
  if (result.error || result.status !== 0) {
    throw new Error(
      `Codex could not disable memories: ${(result.stderr || result.stdout || result.error?.message).trim()}`,
    );
  }
  if (memoryEnabled())
    throw new Error(
      "Codex reported success but the memories feature is still enabled.",
    );
  console.log(
    "Codex built-in Memory disabled and verified. Restart Codex before first Memex sync/backfill.",
  );
}

main().catch((error) => {
  console.error(`memex setup: ${error.message}`);
  process.exit(1);
});
